FROM quay.io/centos/centos:stream9

WORKDIR /root
RUN dnf update -y && \
dnf install -y 'dnf-command(config-manager)'

RUN dnf install -y epel-release
RUN dnf config-manager --set-enabled crb

RUN dnf install -y hostname \
		   git \
		   make \
		   gcc \
                   podman \
		   g++ \
                   bluechi-agent \
		   bluechi-ctl \
		   bluechi-selinux \
		   rpm-build \
		   container-selinux \
		   golang-github-cpuguy83-md2man \
		   selinux-policy \
                   iproute \
                   iproute-devel \
		   iputils \
                   systemd-devel \
                   selinux-policy-devel


RUN git clone https://github.com/containers/qm.git
RUN cd qm && make kvm_subpackage && make rpm && cd rpmbuild/RPMS/noarch && dnf install -y ./*.rpm

# Bluechi

RUN systemctl enable bluechi-controller && \
systemctl enable bluechi-agent

# Controller settings
RUN echo -e "[bluechi-controller]\nNodeName=bluechi_controller\nAllowedNodeNames=spaceship_base,engine1_spaceship,engine2_spaceship,engine3_spaceship,engine4_spaceship\n" > /etc/bluechi/controller.conf.d/controller.conf

# Agent settings
RUN echo -e "[bluechi-agent]\nNodeName=engine1_spaceship\nControllerHost=127.0.0.1\nControllerPort=842\n" > /etc/bluechi/agent.conf.d/agent.conf

# Dynamically fetch IP and append to /etc/hosts
RUN IP=$(hostname -I | awk '{print $1}') && echo "$IP bluechi_controller" >> /etc/hosts

ENTRYPOINT ["tail", "-f", "/dev/null"]
