# How to build
# ==================
# podman login quay.io
# podman build -t quay.io/qm-images/space-grade-linux:latest -f Containerfile
# podman run -it --name space-grade-container quay.io/qm-images/space-grade-linux:latest
# podman push quay.io/qm-images/space-grade-linux:latest
FROM quay.io/centos/centos:stream9

WORKDIR /root
RUN dnf update -y && \
dnf install -y 'dnf-command(config-manager)'

RUN dnf install -y epel-release
RUN dnf config-manager --set-enabled crb

RUN dnf install -y hostname \
		   git \
		   make \
		   gcc \
                   podman \
		   g++ \
		   bluechi \
                   bluechi-agent \
		   bluechi-ctl \
		   bluechi-selinux \
		   rpm-build \
		   container-selinux \
		   golang-github-cpuguy83-md2man \
		   selinux-policy \
                   iproute \
                   iproute-devel \
		   iputils \
                   systemd-devel \
                   selinux-policy-devel
                   #stellarium \
                   #stellarium-data

RUN git clone https://github.com/containers/qm.git
RUN cd qm && make kvm_subpackage && make rpm && cd rpmbuild/RPMS/noarch && dnf install -y ./*.rpm

# or install via dnf install from the rhcontainerbot/qm REPO
#RUN dnf copr enable -y rhcontainerbot/qm centos-stream-9-$(arch)
#RUN dnf install qm -y

RUN /usr/share/qm/setup --skip-systemctl --hostname localrootfs

# Disable blockage of sched_* for realtime
RUN sed -i '/^SeccompProfile=\/usr\/share\/qm\/seccomp\.json/s/^/#/' /usr/share/containers/systemd/qm.containe
RUN systemctl restart qm

# Bluechi

RUN systemctl enable bluechi-controller && \
systemctl enable bluechi-agent

# Controller settings
RUN echo -e "[bluechi-controller]\nNodeName=bluechi_controller\nAllowedNodeNames=spaceship_base,engineX-spaceship\n" > /etc/bluechi/controller.conf.d/controller.conf

# Agent settings
RUN echo -e "[bluechi-agent]\nNodeName=engine1-spaceship\nControllerHost=127.0.0.1\nControllerPort=842\n" > /etc/bluechi/agent.conf.d/agent.conf

# Dynamically fetch IP and append to /etc/hosts
RUN IP=$(hostname -I | awk '{print $1}') && echo "$IP bluechi_controller" >> /etc/hosts

ENTRYPOINT ["/sbin/init"]
