FROM quay.io/centos/centos:stream9

WORKDIR /root
RUN dnf update -y && \
dnf install -y 'dnf-command(config-manager)'

RUN dnf install -y epel-release
RUN dnf config-manager --set-enabled crb

RUN dnf install -y hostname \
		   git \
		   make \
		   gcc \
		   g++ \
		   rpm-build \
		   container-selinux \
		   golang-github-cpuguy83-md2man \
		   selinux-policy \
                   systemd-devel \
                   selinux-policy-devel


RUN git clone https://github.com/containers/qm.git
RUN cd qm && make rpm && cd rpmbuild/RPMS/noarch && dnf install -y ./*.rpm

# or install via dnf install from the rhcontainerbot/qm REPO
#RUN dnf copr enable -y rhcontainerbot/qm centos-stream-9-$(arch)
#RUN dnf install qm -y

RUN /usr/share/qm/setup --skip-systemctl --hostname localrootfs
ENTRYPOINT ["/sbin/init"]
