#!/bin/bash

pushd ../distro/json/
    mkdir -p output
    sudo podman run \
    --rm \
    -it \
    --privileged \
    --pull=newer \
    --security-opt label=type:unconfined_t \
    -v ./config.toml:/config.toml:ro \
    -v ./output:/output \
    -v /var/lib/containers/storage:/var/lib/containers/storage \
    quay.io/centos-bootc/bootc-image-builder:latest \
    --type qcow2 \
    --local \
    quay.io/centos-bootc/centos-bootc:stream9
    echo -e "\nListing qcow2 image from distro/json/output/qcow2/..."
    echo -e "===========================================\n"
    ls output/qcow2/

    sudo virt-install \
    --name centos-bootc \
    --cpu host \
    --vcpus 4 \
    --memory 16096 \
    --import --disk ./output/qcow2/disk.qcow2,format=qcow2 \
    --os-variant fedora-eln \
    --noautoconsole

    sudo virsh list
popd
