#!/bin/bash

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root." >&2
   exit 1
fi

crew_espace_system/run
flight_termination_system/run
heat_shield_protection/run
life_support_system/run
